<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="lynx_al5d">

    <xacro:property name="package_name" value="lynx_al5d_ros2_description"/>
    <xacro:property name="mesh_path" value="package://${package_name}/meshes/robot_parts/"/>
    <xacro:property name="PI" value="3.1415926535897931"/>

    <xacro:property name="shoulder_to_elbow" value="0.146" />
    <xacro:property name="tube_length" value="0.15" />
    <xacro:property name="hs_755eb_depth" value="0.05" />
    <xacro:property name="gripper_base_width" value="0.03175" />

    <xacro:property name="base_mass" value="2.0" />
    <xacro:property name="top_box_mass" value="1.0" />
    <xacro:property name="shoulder_mass" value="0.5" />
    <xacro:property name="hs_755eb_mass" value="0.11" />
    <xacro:property name="hs_645_mass" value="0.05" />

    <xacro:macro name="inertial_matrix_bis" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001" />
        </inertial>
    </xacro:macro>

    <link name="world" />

    <link name="support_link">
        <visual>
            <geometry><mesh filename="${mesh_path}support.dae"/></geometry>
        </visual>
        <collision>
            <geometry><mesh filename="${mesh_path}support.dae"/></geometry>
        </collision>
        <xacro:inertial_matrix_bis mass="${base_mass}"/>
    </link>

    <link name="rotation_cylinder_link">
        <visual>
            <geometry><mesh filename="${mesh_path}rotation_cylinder.dae"/></geometry>
            <origin rpy="0 0 0" xyz="0 -0.021 0" />
        </visual>
        <collision>
            <geometry><mesh filename="${mesh_path}rotation_cylinder.dae"/></geometry>
            <origin rpy="0 0 0" xyz="0 -0.021 0" />
        </collision>
        <xacro:inertial_matrix_bis mass="0.01"/>
    </link>

    <link name="top_box_link">
        <visual>
            <geometry><mesh filename="${mesh_path}top_box.dae"/></geometry>
            <origin xyz="-0.01 0.03 0" rpy="0 0 ${PI}" />
        </visual>
        <collision>
            <geometry><mesh filename="${mesh_path}top_box.dae"/></geometry>
            <origin xyz="-0.01 0.03 0" rpy="0 0 ${PI}" />
        </collision>
        <xacro:inertial_matrix_bis mass="${top_box_mass}"/>
    </link>

    <link name="shoulder_link">
        <visual>
            <geometry><mesh filename="${mesh_path}shoulder.dae"/></geometry>
            <origin rpy="${-5*PI/8} 0 0" xyz="0.005 -0.0625 0.036" />
        </visual>
        <collision>
            <geometry><mesh filename="${mesh_path}shoulder.dae"/></geometry>
            <origin rpy="${-5*PI/8} 0 0" xyz="0.005 -0.0625 0.036" />
        </collision>
        <xacro:inertial_matrix_bis mass="${shoulder_mass}"/>
    </link>

    <link name="elbow_link">
        <visual>
            <geometry><mesh filename="${mesh_path}elbow.dae"/></geometry>
            <origin rpy="${-PI-0.895} ${PI} 0" xyz="-0.006 ${tube_length - 2*hs_755eb_depth/5} ${-shoulder_to_elbow - 0.018}" />
        </visual>
        <collision>
            <geometry><mesh filename="${mesh_path}elbow.dae"/></geometry>
            <origin rpy="${-PI-0.895} ${PI} 0" xyz="-0.005 ${tube_length - 2*hs_755eb_depth/5 + 0.005} ${-shoulder_to_elbow - 0.02} " />
        </collision>
        <xacro:inertial_matrix_bis mass="${hs_755eb_mass + hs_645_mass}"/>
    </link>

    <link name="wrist_link">
        <visual>
            <geometry><mesh filename="${mesh_path}wrist.dae"/></geometry>
            <origin rpy="${PI} 0 0" xyz="0.005 -0.165 0.0695" />
        </visual>
        <collision>
            <geometry><mesh filename="${mesh_path}wrist.dae"/></geometry>
            <origin rpy="${PI} 0 0" xyz="0 -0.165 0.067" />
        </collision>
        <xacro:inertial_matrix_bis mass="0.031" />
    </link>

    <link name="gripper_link">
        <visual>
            <geometry><mesh filename="${mesh_path}gripper.dae"/></geometry>
            <origin rpy="${PI/2} 0 ${-PI/2}" xyz="0 -0.02 0.0" />
        </visual>
        <collision>
            <geometry><mesh filename="${mesh_path}gripper.dae"/></geometry>
            <origin rpy="${PI/2} 0 ${-PI/2}" xyz="0 -0.02 0" />
        </collision>
        <xacro:inertial_matrix_bis mass="0.042" />
    </link>

    <link name="right_finger_link">
        <visual>
            <geometry><mesh filename="${mesh_path}finger_right.dae"/></geometry>
            <origin rpy="${PI/2} 0 ${-PI/2}" xyz="-0.003 -0.005 0" />
        </visual>
        <collision>
            <geometry><mesh filename="${mesh_path}finger_right.dae"/></geometry>
            <origin rpy="${PI/2} 0 ${-PI/2}" xyz="-0.003 -0.005 0" />
        </collision>
        <xacro:inertial_matrix_bis mass="0.002" />
    </link>

    <link name="left_finger_link">
        <visual>
            <geometry><mesh filename="${mesh_path}finger_left.dae"/></geometry>
            <origin rpy="${PI/2} 0 ${-PI/2}" xyz="0.001 -0.005 0" />
        </visual>
        <collision>
            <geometry><mesh filename="${mesh_path}finger_left.dae"/></geometry>
            <origin rpy="${PI/2} 0 ${-PI/2}" xyz="0.001 -0.005 0" />
        </collision>
        <xacro:inertial_matrix_bis mass="0.002" />
    </link>


    <joint name="world_to_robot" type="fixed">
        <parent link="world" />
        <child link="support_link" />
        <origin rpy="0 0 ${PI}" xyz="0 0 0"/>
    </joint>

    <joint name="joint_base_rotate" type="revolute">
        <parent link="support_link" />
        <child link="rotation_cylinder_link" />
        <axis xyz="0 0 -1" />
        <origin xyz="0 0.02 0" rpy="0 0 ${PI}" />
        <limit effort="100" velocity="3" lower="${-PI}" upper="${PI}" />
    </joint>

    <joint name="joint_cylinder_to_box" type="fixed">
        <parent link="rotation_cylinder_link" />
        <child link="top_box_link" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <joint name="joint_shoulder" type="revolute">
        <parent link="top_box_link" />
        <child link="shoulder_link" />
        <axis xyz="1 0 0"/>
        <origin xyz="0 0.02 0.07" />
        <limit effort="100" velocity="3" lower="0" upper="${PI}" />
    </joint>

    <joint name="joint_elbow" type="revolute">
        <parent link="shoulder_link" />
        <child link="elbow_link" />
        <axis xyz="1 0 0" />
        <origin xyz="0 ${shoulder_to_elbow} 0" />
        <limit effort="100" velocity="3" lower="${-PI}" upper="0" />
    </joint>

    <joint name="joint_wrist" type="revolute">
        <parent link="elbow_link" />
        <child link="wrist_link" />
        <axis xyz="1 0 0" />
        <origin xyz="0 0.181 0.005" rpy="0 0 0"/>
        <limit effort="40" velocity="3" lower="${-PI/2}" upper="${PI/2}" />
    </joint>

    <joint name="joint_gripper_rotate" type="revolute">
        <parent link="wrist_link" />
        <child link="gripper_link" />
        <axis xyz="0 -1 0" />
        <origin xyz="0 0.04 0" rpy="0 0 ${PI}" />
        <limit effort="100" velocity="3" lower="${-PI}" upper="${PI}" />
    </joint>

    <joint name="joint_gripper_finger" type="prismatic">
        <parent link="gripper_link" />
        <child link="right_finger_link" />
        <origin xyz="-0.005 -0.015 0" />
        <axis xyz="-1 0 0" />
        <limit effort="100" velocity="0.1" lower="0" upper="${gripper_base_width/2}" />
        <dynamics damping="1.0" friction="0.16" />
    </joint>

    <joint name="joint_gripper_left_finger" type="prismatic">
        <parent link="gripper_link" />
        <child link="left_finger_link" />
        <origin xyz="0.005 -0.015 0" />
        <axis xyz="1 0 0" />
        <mimic joint="joint_gripper_finger" multiplier="1.0" offset="0" />
        <limit effort="100" velocity="0.1" lower="0" upper="${gripper_base_width/2}" />
        <dynamics damping="1.0" friction="0.16" />
    </joint>

    <ros2_control name="GazeboSystem" type="system">
        <hardware>
            <plugin>gazebo_ros2_control/GazeboSystem</plugin>
        </hardware>
        
        <joint name="joint_base_rotate">
            <command_interface name="position"/>
            <state_interface name="position"/>
        </joint>
        <joint name="joint_shoulder">
            <command_interface name="position"/>
            <state_interface name="position"/>
        </joint>
        <joint name="joint_elbow">
            <command_interface name="position"/>
            <state_interface name="position"/>
        </joint>
        <joint name="joint_wrist">
            <command_interface name="position"/>
            <state_interface name="position"/>
        </joint>
        <joint name="joint_gripper_rotate">
            <command_interface name="position"/>
            <state_interface name="position"/>
        </joint>
        
        <joint name="joint_gripper_finger">
            <command_interface name="position"/>
            <state_interface name="position"/>
        </joint>
    </ros2_control>

    <gazebo>
        <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
            <parameters>$(find ${package_name})/config/robot_control.yaml</parameters>
        </plugin>
    </gazebo>

</robot>
